version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gupsppmbot
      - DB_USER=user
      - DB_PASSWORD=password
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS:-[]}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=8000
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: gupsppmbot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  db_data: